spring:
  application:
    name: flowmate-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flowmate
    username: postgres
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
  type-aliases-package: com.flowmate.backend.user.domain,com.flowmate.backend.project.domain,com.flowmate.backend.task.domain

jwt:
  secret: 6364b0d2de554d3e942b1b8b048345251ce116d2a7264276973bb342f0e55def
  iss: nextit.or.kr
  sub: myapp-jwt
  expiration-milliseconds: 604800000

cookie:
  jwt:
    name: jwt_cookie
    http-only: false
    secure: false
    path: /
    maxAge: 604800
